module.exports = async function (context, req) {
    const data = "[{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": \"Present\", \"drizzle\": null, \"hail\": \"Present\", \"fastest2minwindspeed\": 14.1, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": \"Present\", \"temperaturemin\": 27, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 42, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": \"Present\", \"highwind\": null, \"date\": \"2009-01-02\", \"precipitation\": 0.05, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 6.26, \"fastest2minwinddir\": 220, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": null, \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 13.0, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": null, \"temperaturemin\": 15, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 28, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": null, \"highwind\": null, \"date\": \"2009-01-16\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 4.47, \"fastest2minwinddir\": 300, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": \"Present\", \"drizzle\": null, \"hail\": \"Present\", \"fastest2minwindspeed\": 17.0, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": \"Present\", \"temperaturemin\": 32, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 41, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": \"Present\", \"highwind\": null, \"date\": \"2009-01-18\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 10.51, \"fastest2minwinddir\": 210, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": null, \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 17.0, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": null, \"temperaturemin\": 31, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 60, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": null, \"highwind\": null, \"date\": \"2009-01-23\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 8.05, \"fastest2minwinddir\": 240, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": null, \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 14.1, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": null, \"temperaturemin\": 40, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 66, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": null, \"highwind\": null, \"date\": \"2009-02-09\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 6.04, \"fastest2minwinddir\": 100, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": \"Present\", \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 25.1, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": \"Present\", \"temperaturemin\": 48, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 73, \"blowingsnow\": \"Present\", \"freezingrain\": null, \"rain\": null, \"highwind\": null, \"date\": \"2009-02-10\", \"precipitation\": 0.0, \"fogheavy\": \"Present\", \"smokehaze\": \"Present\", \"avgwindspeed\": 10.51, \"fastest2minwinddir\": 230, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": null, \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 17.9, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": null, \"temperaturemin\": 45, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 63, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": \"Present\", \"highwind\": null, \"date\": \"2009-02-14\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 8.72, \"fastest2minwinddir\": 240, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": null, \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 14.1, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": null, \"temperaturemin\": 34, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 54, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": null, \"highwind\": null, \"date\": \"2009-02-15\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 4.7, \"fastest2minwinddir\": 30, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": null, \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 12.1, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": null, \"temperaturemin\": 23, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 50, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": null, \"highwind\": null, \"date\": \"2009-02-17\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 3.8, \"fastest2minwinddir\": 220, \"fastest5secwinddir\": null}," + 
"{\"fogground\": null, \"snowfall\": 0.0, \"dust\": null, \"snowdepth\": 0.0, \"mist\": null, \"drizzle\": null, \"hail\": null, \"fastest2minwindspeed\": 12.1, \"thunder\": null, \"glaze\": null, \"snow\": null, \"ice\": null, \"fog\": null, \"temperaturemin\": 26, \"fastest5secwindspeed\": null, \"freezingfog\": null, \"temperaturemax\": 49, \"blowingsnow\": null, \"freezingrain\": null, \"rain\": null, \"highwind\": null, \"date\": \"2020-12-19\", \"precipitation\": 0.0, \"fogheavy\": null, \"smokehaze\": null, \"avgwindspeed\": 2.91, \"fastest2minwinddir\": 240, \"fastest5secwinddir\": null}]";

    context.res = {
      headers: {
        'Cache-Control': 'private, no-cache, no-store, must-revalidate'
        'Expires': '-1'
      },
      body: { 
        text: data 
      }
    };
  };
